version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/app

  persona-backend:
    build: ./persona-service/backend
    ports:
      - "5001:5001"
    env_file:
      - ./persona-service/backend/.env
    volumes:
      - ./persona-service/backend:/app

  persona-frontend:
    build: ./persona-service/frontend
    ports:
      - "5173:5173"
    env_file:
      - ./persona-service/frontend/.env
