#A la par que el mejor
FROM python:3.13.3

ENV WORKERS=4
ENV THREADS=2

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD gunicorn -w ${WORKERS} -k gthread --threads ${THREADS} --bind 0.0.0.0:5002 run:app